### ISSUE TITLE
6.0 file location changes

### ISSUE THREAD

**Issue by OrigSilverwolf** [Sevii77/ffxiv_materialui_accent#3]
I wanted to test this for you since I'm testing the preliminary 6.0 release of material UI. 

Skotlex had to adjust the location of many files for the new UI to work correctly. I'm getting a large number of errors when loading with your plugin (as expected). 

If I can provide any more testing for you, please let me know on discord as I don't use Github too much. 
Silverwolf#0666

Tested with 
Current build of Penumbra: v0.4.5.0
Current version of Material UI: v6.0.0 (Preliminary)
Current version of your plugin 
On dalamud staging current date 12/6/21

**Comment by Sevii77** [comment]
I've already updated the options and all affected textures to the Preliminary version of Material UI. The reason things are not working is because Penumbra hasn't been updated for 6.0 yet. (Also, Material UI doesn't have to be manually installed unless you use the Colors Only option as it downloads and auto-updates Material UI with that off)

**Comment by OrigSilverwolf** [comment]
Ahhh got you, My fault, I thought it was an issue with the files being misplaced. 

When you say colors only option, which are you referring to? 

So I should uninstall my manual and just install it with penumbra when its updated?

**Comment by Sevii77** [comment]
![image](https://user-images.githubusercontent.com/20374966/144907356-27535601-e95a-424c-a8ed-c3579056138b.png)
If that isnt toggled it will download all of Material UI instead of just this repo, unless you wish to use Material UI with textools, then toggle it on, since that is what the option is for.

**Comment by OrigSilverwolf** [comment]
Sorry im not exactly sure what im doing wrong. That not working for me, I have that setting on and its not changing my system when apply is pressed. 
![image](https://user-images.githubusercontent.com/26029079/145050149-0a520cea-c53a-40ad-b982-de4b36af7645.png)

**Comment by Sevii77** [comment]
That's because it requires penumbra, which hasnt been updated for 6.0 yet.
