### ISSUE TITLE
Enmity list icon

### ISSUE THREAD

**Issue by RoelDevs** [Sevii77/ffxiv_materialui_accent#82]
Hey, I just installed the UI mod and was messing around with the settings but I couldn't find what made it so the enmity icons changed to the blocks instead of how they normally look. Is there a way/option to change this because I couldn't find what was causing this?

![H0hmTJd](https://user-images.githubusercontent.com/37228883/175405401-e0ac30d1-f6fa-42d0-865c-4c3548ed2132.png)

**Comment by Cyrox94** [comment]
I actually just started having issues where some of the alternative settings are no longer working such as the enmity bar ive tried re applying and rediscovering but it wont change

**Comment by mekoichi** [comment]
The flat design of the enmity icons is part of the 4K MUI theme by Skotlex, and is not a direct issue with the plugin. You would need to seek out the MUI Discord channel for any alternatives, or look into manually disabling that specific texture yourself - but bear in mind that it will also alter other elements due to the texture those icons are tied to.

As for alternative not working; please remember to reapply the theme once you've added additional mods, and check the configuration tab in the Material UI mod settings in Penumbra, and make sure the alternative icons have been selected. Once you've done this, make sure you restart your game to ensure all textures are correctly loaded in.
